name: Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify code formatting
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

      - name: Lint with Clippy
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      
      - run: cargo clippy

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
